### ISSUE TITLE
ヘルスチェックの何かを作ります

### ISSUE THREAD

**Issue by kkazuma** [ShigeruIchinoki/taem_c_kadai#1]
神山です。
アイディアがあればここに書き込んでください。

**Comment by ShigeruIchinoki** [comment]
当方、前回提出課題で、BMIを作りました。

できれば違う方がよいのですが。
よいアイデアありますか？

数字の関数系だと
最大公約数とか最小公倍数
文字系だと
英字のみ大文字にする

とかでしょうか。よろしくお願いします。

**Comment by ShigeruIchinoki** [comment]
お疲れ様です。
一ノ木です。
作るものですが、他のgemをbundleしてそれを使用するという手もあると思いました。

**Comment by masayuki1984** [comment]
自分は以前「pebbles-soreyuke」という外部のgemを利用してfizzbuzzをアンパンマン達にしゃべらせたことがあります。
この程度の簡単なgemなら使用しても作業の負担にならないと思います。
参考:http://qiita.com/fukayatsu/items/19807642971ebcc92f52

**Comment by ShigeruIchinoki** [comment]
お疲れ様です。
pebbles-soreyuke面白そうで、良さげです。

あと、テストのオプションをつけるのを忘れてしまっていたので、不足分ファイル追加しておきました。今気づいたのですが、アプリ名タイポしています。。teamが正しいです。すいません。
気にならないならばそのまま続けますが、どうでしょう。

**Comment by masayuki1984** [comment]
http://ndtot.up.seesaa.net/image/E382A2E38386E3838DE4B88DE79CA0E5B0BAE5BAA6EFBC88AISEFBC89.pdf
不眠度チェックというのを見つけました。

実装も簡単そうだし健康に関連したものなのでネタになるかと思いました。
ちなみに私は1点なので睡眠はとれているようです。

あと、タイポは気にならないです。

**Comment by kkazuma** [comment]
お疲れ様です。
仕事であんまり追えてなくてすみません。
自分もこんなのを調べました。共有までに

①基礎代謝量
https://ja.wikipedia.org/wiki/%E5%9F%BA%E7%A4%8E%E4%BB%A3%E8%AC%9D

②1日に必要なカロリー
https://www.med.or.jp/forest/health/eat/01.html

③いろんな運動のカロリー消費
http://www.aikido.ne.jp/sec01_0501.html

なんとなく調べていての思いつきですが、

１、基礎代謝量計算
２、1日に必要なカロリー計算
３、そのカロリーを消費するためにどんな運動が必要かを計算
４、計算した結果をアンパンマンに喋らせる

みたいなGemができたら面白そうだし、１、２は式を当てはめるだけだし３はいろんな運動を引っ張ってくればよいし簡単かなと

あとはオプションでBMI指数からアンパンマンを太らせたりできたら面白そう

**Comment by sasai** [comment]
@sasai です、どうもおそくなりました。
以下に健康関係の各種計算式がのってました。
　http://www.h-nc.com/cat3/calculation-list/
@kkazuma さんの言うように、計算結果に加えて、アドバイスまでするといいですね。

@ShigeruIchinoki さん、
リポジトリ名は右サイドバーの「Settings」をクリックして「Repository name」を「Rename」
するだけで簡単に変更できます。

**Comment by kkazuma** [comment]
神山です。
連絡方法が無かったのでここに書いておきますが、電車遅延で15時くらいに着きますので、皆さんで進めておいてください。

すいません！

**Comment by masayuki1984** [comment]
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ./taem_c_kadai/fumin.rb (LoadError)
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from lib/taem_c_kadai.rb:2:in `<main>'

**Comment by masayuki1984** [comment]
新しくディレクトリ作ってgit cloneしたら問題なく動作しました。

**Comment by kkazuma** [comment]
不眠関数用意しました。
TESTは入力が絡むのでできてません。動かないかもしれません

**Comment by sasai** [comment]
pull requestたまってきたので一旦マージしますね。

**Comment by ShigeruIchinoki** [comment]
皆様お疲れさまです。
pullしたものをgem化してirbでrequireはできました。
申し訳ありませんが、具体的な使い方の共有をしていただけると助かります。

**Comment by sasai** [comment]
きちんと動いていなかったので修正してマージしました。
できたgemをインストールして、コンソールから taem_c_kadai を実行すると動きます。

**Comment by masayuki1984** [comment]
今プルリしているのをマージすると、irbで「require taem_c_kadai」実行後、TaemCKadai.ask()でアンパンマンがいろいろ尋ねてきます。
BMIは完了、カロリー系は細かいメソッドは未実装だが基礎代謝量は実装済み。不眠は未実装です。

**Comment by kkazuma** [comment]
不眠修正して実装までやってマージしました。
git pull して使ってみてください。
何か要望あれば修正します。

とりあえずは暫定完成ですかね？

**Comment by masayuki1984** [comment]
完成度を高めるならfunc_fuminの入力する際には0~3以外の数字は受け付けない仕組みが欲しいかなとは思います。

**Comment by kkazuma** [comment]
たしかに。それは思った。
あとはBMIと同様に中の質問もアンパンマンとかにしたかったんだけど、二行以上あると崩れてしまう？

**Comment by kkazuma** [comment]
あと今気づいたんですが、不眠度の３と８の質問は全く一緒なんですね笑
元のサイトも同じなので問題はないのですが・・・

**Comment by masayuki1984** [comment]
2行以上は崩れますね。
質問が同じなのは気づいていたんですけどギリシャ人だから適当なのかなと思ってました。

**Comment by kkazuma** [comment]
０から３しか入力できなくしました

**Comment by ShigeruIchinoki** [comment]
:+1: gem化してしてうまく動いているのを確認しました。
